#server
server:
  port: 8001
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: ./logs
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd
#log
logging:
  config: classpath:logback.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet-path}
  health-check-url-path: ${server.servlet-path}/health

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 2000

spring:
  application:
    name: h-seckill-front-web-dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  session:
    store-type: redis
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
service:
  h-seckill-front:
    name: h-seckill-front-dev
    path: /front
#distributed-lock:
#  timeout: 1000