server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
      sensitive: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server